    server {
    if ($host = ai-mindnovation.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	server_name ai-mindnovation.com;
	location / {
	    proxy_pass http://10.0.0.5:8030;
	    proxy_redirect off;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	#return 301 https://aserprem.com.co$request_uri;
	add_header 'Content-Security-Policy' 'upgrade-insecure-requests';	
    }


    listen 80;



}
