    server {
	server_name analytics.gestorconsultoria.com.co;
	location / {
	    proxy_pass http://10.0.0.2:8039;
	    proxy_redirect off;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	#return 301 https://aserprem.com.co$request_uri;
    }


    listen 80; 
}

