server {
    server_name team.gestorconsultoria.com.co;
    location / {
        proxy_pass http://10.0.0.5:6016; # Pruebas
	#proxy_pass http://192.168.100.200:8016; # Produccion
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/team.gestorconsultoria.com.co/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/team.gestorconsultoria.com.co/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = team.gestorconsultoria.com.co) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name team.gestorconsultoria.com.co;


    listen 80;
    return 404; # managed by Certbot


}