server {
    server_name www.gestorconsultoria.com.co;
    location / {
        proxy_pass http://192.168.100.200:8081;
        # proxy_redirect off;
	proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Proto 'https';
       
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/www.gestorconsultoria.com.co/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.gestorconsultoria.com.co/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = www.gestorconsultoria.com.co) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name www.gestorconsultoria.com.co;

    listen 80;
    return 404; # managed by Certbot


}