services:
  web:
    #image: odoo-team:13
    image: odoo:13
    restart: "always"
    depends_on:
     - db-16
    ports:
     - "8016:8069"
    environment:
     - HOST=db-16
     - USER=odoo
     - PASSWORD=Gestor2020
    volumes:
     - ./config:/etc/odoo
     - ./filestore:/var/lib/odoo/filestore
     - ./extra-addons:/mnt/extra-addons
     - ./postgresql/data/compartida:/mnt/compartida
    command: ["odoo", "--config=/etc/odoo/odoo.conf"]
    healthcheck:
     test: curl --fail http://localhost || exit 1
     interval: 5m00s
     timeout: 20s
     retries: 3
  db-16:
    #image: postgres-team:10.5
    image: postgres:10.5
    # image: postgres:12
    restart: "always"
    ports:
     - "9016:5432"
    volumes:
     - ./postgresql/data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_PASSWORD=Gestor2020
     - POSTGRES_USER=odoo

  db-16-12:
    image: postgres:12
    restart: "always"
    ports:
     - "9017:5432"
    volumes:
    - ./postgresql/data_pg_12:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=postgres
     - POSTGRES_PASSWORD=Gestor2020
     - POSTGRES_USER=odoo
